services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile_app
      target: development
    volumes:
      - .:/app 
      - bundle-data:/app/vendor/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:example@db:5432/myapp_development
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
      #ホントはここに書いちゃだめ env.exampleにキー名とダミー入れて本物は１passwordとかで管理
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: 
  bundle-data:  
