# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.4.5

# ビルド用ステージ
FROM ruby:${RUBY_VERSION}-slim AS builder

RUN apt-get update -q && apt-get install -y --no-install-recommends \
    build-essential curl git libvips postgresql-client libyaml-dev \
    && rm -rf /var/lib/apt/lists/* && apt-get clean

WORKDIR /app
COPY Gemfile Gemfile.lock ./

RUN gem install bundler -v 2.6.7
RUN bundle _2.6.7_ config set path 'vendor/bundle'
RUN bundle _2.6.7_ install --deployment --without development test

COPY . .

#production
FROM ruby:${RUBY_VERSION}-slim AS production
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    libvips postgresql-client libyaml-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR /app
COPY --from=builder /app /app

#development
FROM builder AS development
RUN bundle config unset without && bundle config unset deployment \
    && apt-get update \
    && apt-get install -y --no-install-recommends locales ripgrep \
    && sed -i 's/# *ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen ja_JP.UTF-8 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
ENV LANG="ja_JP.UTF-8" LC_ALL="ja_JP.UTF-8"