# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.4.5

# ビルド用ステージ
FROM ruby:${RUBY_VERSION}-slim AS builder

RUN apt-get update -q && apt-get install -y --no-install-recommends \
    build-essential curl git libvips postgresql-client libyaml-dev \
    && rm -rf /var/lib/apt/list/*

WORKDIR /app
COPY Gemfile Gemfile.lock ./

RUN gem install bundler -v 2.6.7
RUN bundle install --deployment --without development test

COPY . .

FROM ruby:${RUBY_VERSION}-slim
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    libvips postgresql-client libyaml-dev \
    && rm -rf /var/lib/apt/list/*

WORKDIR /app
COPY --from=builder /app /app